stackBot:
  # Publish all joints ---------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  #Position Controllers --------------------------------
  leftWheel_Joint_position_controller:
    type: effort_controllers/JointVelocityController
    joint: leftWheel_Joint
    pid: {p: 3.0, i: 1.0, d: 0.0}
  
  rightWheel_joint_position_controller:
    type: effort_controllers/JointVelocityController
    joint: rightWheel_joint
    pid: {p: 3.0, i: 1.0, d: 0.0}
